title: <p align="center"> Gavin Ong </p>

description:
  <p align="center">
  <a href="pdf/Gavin_Resume_vA.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gavinongzekai">LinkedIn Profile</a> | 
  <a href="https://github.com/gavinongzk">GitHub</a>
  </p>
  
  <p>
  I am currently a Data Analyst at Enterprise Singapore with a focus on building data pipelines and visualizations.
  <br><br>
  </p>




theme: jekyll-theme-minimal